"""CSV/JSON I/O and report export."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

import numpy as np

from .laws import format_flops, format_params


def load_runs(path: str | Path) -> dict[str, dict[str, np.ndarray]]:
    """Load runs from CSV or JSON.

    CSV columns: N, D, L, optimizer
    JSON: list of objects or {optimizer: [{N,D,L}, ...]}
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".json":
        raw = json.loads(path.read_text(encoding="utf-8"))
        return _normalize_json_runs(raw)
    rows: list[dict[str, Any]] = []
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(
                {
                    "N": float(row["N"]),
                    "D": float(row["D"]),
                    "L": float(row["L"]),
                    "optimizer": row.get("optimizer", "adamw").strip().lower(),
                }
            )
    return _rows_to_runs(rows)


def _normalize_json_runs(raw: Any) -> dict[str, dict[str, np.ndarray]]:
    if isinstance(raw, list):
        return _rows_to_runs(raw)
    if isinstance(raw, dict) and "runs" in raw:
        return _normalize_json_runs(raw["runs"])
    # {opt: [{N,D,L}, ...]}
    out: dict[str, dict[str, np.ndarray]] = {}
    for opt, items in raw.items():
        ns = [float(x["N"]) for x in items]
        ds = [float(x["D"]) for x in items]
        ls = [float(x["L"]) for x in items]
        out[str(opt).lower()] = {
            "N": np.asarray(ns, dtype=float),
            "D": np.asarray(ds, dtype=float),
            "L": np.asarray(ls, dtype=float),
        }
    return out


def _rows_to_runs(rows: list[dict[str, Any]]) -> dict[str, dict[str, np.ndarray]]:
    buckets: dict[str, list[dict[str, float]]] = {}
    for row in rows:
        opt = str(row.get("optimizer", "adamw")).lower()
        buckets.setdefault(opt, []).append(
            {"N": float(row["N"]), "D": float(row["D"]), "L": float(row["L"])}
        )
    out: dict[str, dict[str, np.ndarray]] = {}
    for opt, items in buckets.items():
        out[opt] = {
            "N": np.asarray([x["N"] for x in items], dtype=float),
            "D": np.asarray([x["D"] for x in items], dtype=float),
            "L": np.asarray([x["L"] for x in items], dtype=float),
        }
    return out


def save_allocation_csv(rows: list[dict[str, Any]], path: str | Path) -> None:
    path = Path(path)
    fields = [
        "optimizer",
        "label",
        "N",
        "D",
        "compute",
        "loss",
        "tokens_per_param",
        "rho_n",
        "rho_d",
        "N_ratio_vs_ref",
        "compute_savings_vs_adamw_same_loss",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def save_markdown_report(report: dict[str, Any], path: str | Path) -> None:
    path = Path(path)
    wall = report.get("wallclock", {})
    lines = [
        "# OptiScale Cost Report",
        "",
        f"- Compute: `{wall.get('compute_human', format_flops(wall.get('compute', 0)))}`",
        f"- GPU: **{wall.get('gpu', '?')}** × {wall.get('count', '?')} @ MFU {wall.get('mfu', '?')}",
        f"- Wall-clock: **{wall.get('days', 0):.2f} days** ({wall.get('hours', 0):.1f} h)",
        f"- Estimated cost: **${wall.get('cost_usd', 0):,.0f}**",
        "",
        "## Allocations",
        "",
        "| Optimizer | N* | D* | tok/param | Pred. loss | N ratio vs AdamW |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in report.get("allocations", []):
        lines.append(
            f"| {row.get('label', row.get('optimizer'))} | "
            f"{row.get('N_human', format_params(row['N']))} | "
            f"{row.get('D_human', format_params(row['D']))} | "
            f"{row['tokens_per_param']:.1f} | "
            f"{row['loss']:.4f} | "
            f"{row.get('N_ratio_vs_ref', 1):.3f} |"
        )
    lines.extend(["", "## Savings to match AdamW loss", ""])
    for s in report.get("savings_vs_adamw_loss", []):
        lines.append(
            f"- **{s['label']}**: {s['pct_compute_saved']:.1f}% less compute "
            f"(${s['usd_saved_vs_full_budget']:,.0f} saved at listed GPU rates)"
        )
    lines.extend(
        [
            "",
            "---",
            "_Generated by [OptiScale](https://github.com/spectral-training/optiscale). "
            "ρ defaults are planning priors — fit your own runs for production budgets._",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def export_python_snippet(compute: float, optimizer: str = "muon") -> str:
    return f'''from optiscale import allocate_for_budget, cost_report

alloc = allocate_for_budget({compute:.6e}, optimizer="{optimizer}")
print(alloc["N_human"], alloc["D_human"], alloc["loss"])

report = cost_report(compute={compute:.6e}, gpu_id="h100", count=8)
print(report["wallclock"]["days"], "days")
'''
